API/API/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('calculation/',  include('part2.urls')),
    path('index/',  include('webapp.urls'))
]

API/part2/urls.py
from django.contrib import admin
from django.urls import path

from part2.views import calculate_numbers, add, subtruct, multiply, divide
from webapp.views import Index

app_name = 'calculate'

urlpatterns = [

    path('add/', add, name='add'),
    path('subtruct/', subtruct, name='subtruct'),
    path('multiply/', multiply, name='multiply'),
    path('divide/', divide, name='divide'),
    path('get_token/', calculate_numbers, name='get_token')
]

API/webapp/urls.py
from django.contrib import admin
from django.urls import path
from webapp.views import Index
app_name = 'index'
urlpatterns = [
    path('', Index.as_view(), name='index'),

    # path('get_token/', calculate_numbers, name='get_token')
]

API/part2/models.py
from django.db import models

# Create your models here.

API/part2/views.py
import json

from django.http import HttpResponse, HttpResponseNotAllowed, JsonResponse

from django.views.decorators.csrf import ensure_csrf_cookie


@ensure_csrf_cookie
def calculate_numbers(request, *args):
    if request.method == 'GET':
        return HttpResponse(json.dumps({'token': "ok"}))
    return HttpResponseNotAllowed('Only GET request are allowed')


def add(request):
    if request.method=='POST':
       body = request.body
       data = json.loads(body)
       if not data.get("A") or not data.get('B'):
           response = JsonResponse({'error': 'Введите что нибудь!!'})
           response.status_code = 400
           return response
       try:
            result = int(data['A']) + int(data['B'])
            return JsonResponse({'result': result})
       except:
           response = JsonResponse({'error': "Ввести нужно только числа"})
           response.status_code = 400
           return response



def subtruct(request):
    if request.method == 'POST':
        body = request.body
        data = json.loads(body)
        if not data.get("A") or not data.get('B'):
            response = JsonResponse({'error': 'Введите что нибудь!!'})
            response.status_code = 400
            return response
        try:
            result = int(data['A']) - int(data['B'])
            return JsonResponse({'result': result})
        except:
            response = JsonResponse({'error': "Ввести нужно только числа"})
            response.status_code = 400
            return response

def multiply(request):
    if request.method == 'POST':
        body = request.body
        data = json.loads(body)
        if not data.get("A") or not data.get('B'):
            response = JsonResponse({'error': 'Введите что нибудь!!'})
            response.status_code = 400
            return response
        try:
            result = int(data['A']) * int(data['B'])
            return JsonResponse({'result': result})
        except:
            response = JsonResponse({'error': "Ввести нужно только числа"})
            response.status_code = 400
            return response

def divide(request):
    if request.method == 'POST':
        body = request.body
        data = json.loads(body)
        if not data.get("A") or not data.get('B'):
            response = JsonResponse({'error': 'Введите что нибудь!!'})
            response.status_code = 400
            return response
        try:
            result = int(data['A']) / int(data['B'])
            return JsonResponse({'result': result})
        except:
            response = JsonResponse({'error': "Ввести нужно только числа"})
            response.status_code = 400
            return response

API/webapp/views.py
from django.shortcuts import render
from django.views.generic.base import View


class Index(View):
    def get(self, request, *args, **kwargs):
        return render(self.request, 'index.html')

API/webapp/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>


<input type=text id="value1">
<input type=text id="value2">

    <input type=button value="add" name=add data-url="{% url 'calculate:add' %}" onclick="calculateIntegers(event)">
    <input type=button value="subtract" name=subtract onclick="calculateIntegers(event)" data-url="{% url 'calculate:subtruct' %}">
    <input type=button value="multiply" name=multiply onclick="calculateIntegers(event)" data-url="{% url 'calculate:multiply' %}">
    <input type=button value="divide" name=divide onclick="calculateIntegers(event)" data-url="{% url 'calculate:divide' %}">


<p id="result"></p>



<script src="{% static "js/calculate.js" %}">

</script>

</body>
</html>